blank_issues_enabled: true
contact_links:
  - name: RightSub Documentation & Wiki
    url: https://github.com/omerninyo/RightSub/wiki
    about: Please check the official documentation and guides first before reporting a bug.
